packages = [
    "git",
    "emacs-nox",
    "htop",
    "npm",
    "python3-pip",
    "httpie",
    "mosh",
    "zsh",
    "twine",
    "gist",
    "pcscd",
    "scdaemon",
    "secure-delete",
    "direnv",
    "hub",
    "yadm",
    "mtr-tiny",
    "postgresql-client",
    "ruby",
    "entr",
    "silversearcher-ag",
    "powerline",
    "ranger",
    "curl"
]

debian_packages = [
    "apt-listbugs"
]

py_user_packages = [
	"ipython"
]

gui_packages = [
    "org-mode",
    "lyx",
    "vlc",
    "gitg",
    "xclip",
    "gnome-shell-pomodoro",
    "deluge",
    "darktable",
    "flameshot",
    "terminator"
]
